export const MOVIES = [
  'Maroon 5',
  'James Bay',
  'James Arthur',
  'Abba',
  'Elvis Presley',
  'Tokio Hotel ( Johanna`s favorite band )',
  'Metallica',
  'Foo Fighters',
  'Helene Fischer (for some German Schlager :joy:)',
  'Querbeat (for Cologne Carnival)',
  'Maneskin',
  'Florence + The Machine',
  'Lenny Kravitz',
  'Stromae',
  'Shania Twain',
  'Bastille',
  'Adele',
  'John Legend',
  'Beyonce',
  'Billy Talent',
  'Black Eyed Peas',
  'Destiny’s Child',
  'O-Zone :joy:',
  'Ed Sheeran',
  'Coldplay',
  'Dua Lipa',
  'Lady Gaga',
  ' Rihanna',
  'Avril Lavigne',
  'Justin Bieber',
  'Ariana Grande',
  'Taylor Swift',
  'Jennifer Lopez',
  'Chris Brown',
  'Sid Sriram',
  'AR Rahman',
  'Lata Mangeshkar',
  'SP Balasubramaniam',
  'Arijit Singh',
  '21 Savage',
  'Eminem',
  'Drake',
  'John Lennon',
  'Sam Smith',
  'Future',
  'Doja Cat',
  'David Guetta',
]
