export const MOVIES = [
  'Tyrion',
  'Jon Snow',
  'Joker',
  'Batman',
  'Chandler Bing',
  'Gilfoyle',
  'Samwise Gamgee',
  'Beth Harmon',
  'Grogu',
  'Luna Lovegood',
  'Jim Hopper',
  'Nairobi',
  'Forrest Gump',
  'Groot',
  'Chewbacca',
  'Spock',
  'Varys',
  'William Butcher',
  'Deadpool',
  'Heisenberg',
  'Saul Goodman',
  'Mario',
  'Spiderman',
  'Django',
  'Zoro',
  'Toni Montana',
  'Peter Pan',
  'Norman Bates',
  'Thomas Shelby',
  'Tyler Durden',
  'Elsa',
  'Jordan Belfort',
  'Andy Dufresne',
  'Gregory House',
]
