export const MOVIES = [
  'Maroon 5',
  'James Bay',
  'James Arthur',
  'Abba',
  'Elvis Presley',
  'Tokio Hotel ( Johanna`s favorite band )',
  'Metallica',
  'Foo Fighters',
  'Helene Fischer (for some German Schlager :joy:)',
  'Querbeat (for Cologne Carnival)',
  'Maneskin',
  'Florence + The Machine',
  'Lenny Kravitz',
  'Stromae',
  'Shania Twain',
  'Bastille',
  'Adele',
  'John Legend',
  'Beyonce',
  'Billy Talent',
  'Black Eyed Peas',
  'Destiny’s Child',
  'O-Zone :joy:',
  'Ed Sheeran',
  'Coldplay',
  'Dua Lipa',
  'Lady Gaga',
]
